config/routes.rb
Rails.application.routes.draw do
  resources :pics
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
    has_one_attached :image
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  
  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
    
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
    @pic = Pic.find(params[:id])
    
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)
    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render :show, status: :created, location: @pic }
      else
        format.html { render :new }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
       
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pic_params
      params.require(:pic).permit(:caption, :image)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakeagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pics/_form.html.erb
<%= form_with(model: pic, local: true) do |form| %>
  <% if pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
        <% pic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_area :caption %>
    <%= form.label "Image" %>
    <%= form.file_field :image %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= image-tag(@pic.image)  if @pic.image.attached?%>
<%= render 'form', pic: @pic %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pics</h1>

<table>
  <thead>
    <tr>
      <th>Caption</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pics.each do |pic| %>
      <tr>
        <td><%= pic.caption %></td>
        <td><%= link_to 'Show', pic %></td>
        <td><%= link_to 'Edit', edit_pic_path(pic) %></td>
        <td><%= link_to 'Destroy', pic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pic', new_pic_path %>

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form', pic: @pic %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Caption:</strong>
  <%= @pic.caption %>
</p>

<% if @pic.image.attached?%>
 <image src="<%=(url_for(@pic.image))%>">
<% end %>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>